/**
 * SwarmPortal.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthConfig { 
    authority?: string | null;
    audience?: string | null;
    issuer?: string | null;
    clientId?: string | null;
    redirectUri?: string | null;
    scope?: string | null;
    requireHttps?: boolean;
}

