/**
 * SwarmPortal.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Group } from './group';
import { IRole } from './iRole';


export interface ILink { 
    readonly id?: number;
    readonly name?: string | null;
    readonly url?: string | null;
    group?: Group;
    readonly roles?: Array<IRole> | null;
}

