
entryPoints:
  web:
    address: ":80"
    http:

providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    network: "webhosts"
    exposedbydefault: false
    swarmMode: true

api:
  insecure: true
