name: Build Application 
on:  

  pull_request:
    branches:    
      - main
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '30 5,17 * * *'
  push:    
    branches: 
      - main
jobs:   
  build:    
    runs-on: ubuntu-latest   
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1  
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x.x'
    - name: Build API
      if: success()
      run: |
        dotnet build
    - name: Set up .NET
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Build FrontEnd
      if: success()
      working-directory: ./SwarmPortal.FrontEnd
      run: |
        npm ci
        npm run build
        